105 add timetime service
Epitech-Nantes-Tek3/A-equals-l-squared pull request #126
Opened 2023-02-14 16:02 UTC by LucasTesnier

# Purpose

The purpose of this pull request is to add the service John.

Fixes # (issue)

## Added features

* This service has been added to the application. It includes:
  * A action which is used to ...
  * A reaction which does this ...

## Updated features

* This part has been changed because the new feature needed to be implemented this way.

## Fixed feature

* This features has been fixed.
* This one too.

## Removed features

* This features has been removed because it was unnecessary.

2023-02-14 17:08 UTC, ZQUEMA requested changes
Answer the questions

2023-02-14 17:08 UTC, ZQUEMA commented on server/server_app.js
> +        }
Why do you delete smth in a creation request ?

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/at_a_date.js
> +    const sec = paramsList[3].value != '' ? paramsList[3].value : '0'
Why does it use hard array indexes ? Can't it be like the other actions ?

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/at_a_date.js
> +          value: area.ActionParameters[0].value,
Why does it use hard array indexes ? Can't be like the other actions ?

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/at_a_date.js
> +          value: area.ActionParameters[1].value,
Same as above

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/at_a_date.js
> +          value: area.ActionParameters[2].value,
Same as above

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/at_a_date.js
> +          value: area.ActionParameters[3].value,
Same as above

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/every_x_time.js
> +  return '*/' + parameters[0].value + ' * * * * *'
Why does it use hard array indexes ? Can't be like the other actions ?

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/every_x_time.js
> +          value: area.ActionParameters[0].value,
Why does it use hard array indexes ? Can't be like the other actions ?

2023-02-14 17:08 UTC, ZQUEMA commented on server/services/timetime/actions/every_x_time.js
> +          value: area.ActionParameters[1].value,
Same as above

2023-02-14 17:34 UTC, LucasTesnier commented on server/server_app.js
> +        }
If the Trigger init failed (For some bad parameters meaning or other things) we need to delete the newly created area.

2023-02-15 08:37 UTC, tbellicha submitted a review, later dismissed
NTR

2023-02-15 09:30 UTC, TomDUVAL-MAHE approved these changes
NTR

2023-02-15 12:13 UTC, ZQUEMA approved these changes

2023-02-15 12:13 UTC, ZQUEMA commented on server/server_app.js
> +        }
If smth failled, the prisma query will send a error and won't create the service

2023-02-15 12:13 UTC, merged