112 handle dynamic parameters
Epitech-Nantes-Tek3/A-equals-l-squared pull request #127
Opened 2023-02-14 16:10 UTC by ZQUEMA

# Purpose

The purpose of this pull request is to handle the dynamic parameters as variable in the reaction.

Fixes #112 

## Added features

* New Model to store dynamic parameters
* Reaction can now use the dynamic parameters of a linked action.

## Updated features

* Action model has now dynamic parameters

2023-02-14 16:18 UTC, LucasTesnier requested changes
Some minor things to fix.

Is the Delete area work with the new Database scheme ?

2023-02-14 16:18 UTC, LucasTesnier commented on server/prisma/schema.prisma
> +  Action      Action  @relation(fields: [actionId], references: [id])
Missing onDelete and onUpdate field

2023-02-14 16:18 UTC, LucasTesnier commented on server/services/discord/actions/on_join_voice_channel.js
> +    const dynamicParameters = [
Format the code

2023-02-14 16:47 UTC, ZQUEMA commented on server/prisma/schema.prisma
> +  Action      Action  @relation(fields: [actionId], references: [id])
Yes, it does

2023-02-14 16:49 UTC, ZQUEMA commented on server/services/discord/actions/on_join_voice_channel.js
> +    const dynamicParameters = [
Done

2023-02-15 08:14 UTC, LucasTesnier approved these changes, later dismissed

2023-02-15 08:46 UTC, tbellicha approved these changes

2023-02-15 09:02 UTC, LucasTesnier approved these changes

2023-02-15 09:02 UTC, merged