117 implement deezer service
Epitech-Nantes-Tek3/A-equals-l-squared pull request #130
Opened 2023-02-15 09:06 UTC by tbellicha

# Purpose

The purpose of this pull request is to add the service John.

Fixes # (issue)

## Added features

* This service has been added to the application. It includes:
  * A action which is used to ...
  * A reaction which does this ...

## Updated features

* This part has been changed because the new feature needed to be implemented this way.

## Fixed feature

* This features has been fixed.
* This one too.

## Removed features

* This features has been removed because it was unnecessary.

2023-02-26 18:07 UTC, LucasTesnier requested changes
Answer request

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/common/add_tracks_to_playlist.js
> +async function addTracksToPlaylist (playlistId, tracksId, deezerToken) {
Missing doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/getters/user_playlists.js
> +async function getUserPlaylists (deezerId, deezerToken) {
Missing doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/init.js
> +        icon: '',
Where's the icon ?

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/init.js
> +        Actions: {
If there's now action please do not add a false one

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/init.js
> +                'Add a few tracks of your history to a owned playlist',
Maybe an X param ? For "few"

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/add_history_to_playlist.js
> +async function deezerAddHistoryToPlaylistFromArea (Area, dynamicParameters) {
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/add_history_to_playlist.js
> +async function addHistoryToPlaylist (playlistId, deezerId, deezerToken) {
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/add_recommendations_to_playlist.js
> +async function deezerAddRecommendationsToPlaylistFromArea (
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/add_recommendations_to_playlist.js
> +async function addRecommendationsToPlaylist (playlistId, deezerId, deezerToken) {
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/clear_playlist.js
> +
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/clear_playlist.js
> +
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/create_playlist.js
> +function deezerCreatePlaylistFromArea (Area, dynamicParameters) {
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/create_playlist.js
> +async function createPlaylist (title, deezerId, deezerToken) {
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/delete_playlist.js
> +function deezerDeletePlaylistFromArea (Area, dynamicParameters) {
Doc

2023-02-26 18:07 UTC, LucasTesnier commented on server/services/deezer/reactions/delete_playlist.js
> +async function deletePlaylist (playlistId, deezerToken) {
Doc

2023-02-26 18:21 UTC, ZQUEMA requested changes
Some needed changes

2023-02-26 18:21 UTC, ZQUEMA commented on server/server_app.js
> + */
complete the documentation with the needed body fields

2023-02-26 18:21 UTC, ZQUEMA commented on server/services/deezer/init.js
> +                'Add a few tracks of your recommendations to a owned playlist',
Same as above

2023-02-27 08:02 UTC, LucasTesnier requested changes
doc

2023-02-27 08:02 UTC, LucasTesnier commented on server/server_app.js
> +app.get(
missing doc

2023-02-27 08:13 UTC, TomDUVAL-MAHE approved these changes, later dismissed

2023-02-27 08:44 UTC, TomDUVAL-MAHE approved these changes, later dismissed

2023-02-27 09:00 UTC, LucasTesnier approved these changes, later dismissed

2023-02-27 09:32 UTC, ZQUEMA approved these changes

2023-02-27 09:32 UTC, LucasTesnier approved these changes

2023-02-27 09:57 UTC, merged