add calendar create event
Epitech-Nantes-Tek3/A-equals-l-squared pull request #150
Opened 2023-02-20 15:57 UTC by GuyomT

# Purpose

The purpose of this pull request is to add the service Google Calendar.

Fixes # (issue)

## Added features

* This service has been added to the application. It includes:
  * A reaction which create an event in the calendar

2023-02-20 16:16 UTC, ZQUEMA requested changes
Needed changes

2023-02-20 16:16 UTC, ZQUEMA commented on server/services/calendar/calendar_init.js
> +                icon: './assets/icons/calendar.png',
Did you add the icon ?

2023-02-20 16:16 UTC, ZQUEMA commented on server/services/calendar/calendar_init.js
> +                            code: 'CAL-02',
Why is it '02' and not '01' ?

2023-02-21 11:55 UTC, tbellicha requested changes

2023-02-21 11:55 UTC, tbellicha commented on server/services/calendar/calendar_init.js
> +                            name: 'create_event',
Use CamelCase instead

2023-02-21 11:55 UTC, tbellicha commented on server/services/calendar/reactions/create_event.js
> +const createEventWithAccessToken = async (accessToken, calendarId, summary, description, start, end) => {
Missing docs

2023-02-21 11:55 UTC, tbellicha commented on server/services/calendar/reactions/create_event.js
> +const calendarCreateEventFromArea = async (Area, dynamicParameters) => {
Missing docs

2023-02-21 12:28 UTC, ZQUEMA approved these changes

2023-02-21 13:54 UTC, tbellicha approved these changes

2023-02-23 08:34 UTC, merged