153 add reddit service
Epitech-Nantes-Tek3/A-equals-l-squared pull request #171
Opened 2023-02-28 13:11 UTC by tbellicha

# Purpose

The purpose of this pull request is to add the service John.

Fixes #153

## Added features

* This service has been added to the application. It includes:
  * A action which is used to ...
  * A reaction which does this ...

## Updated features

* This part has been changed because the new feature needed to be implemented this way.

## Fixed feature

* This features has been fixed.
* This one too.

## Removed features

* This features has been removed because it was unnecessary.

2023-03-01 10:48 UTC, LucasTesnier requested changes
Missing doc and add reddit icon otherwise NTR goat

2023-03-01 10:48 UTC, LucasTesnier commented on server/server_app.js
> + * Generate token thanks to a code in Reddit
missing doc

2023-03-01 10:48 UTC, LucasTesnier commented on server/services/reddit/init.js
> +        icon: '',
Missing icon

2023-03-01 11:03 UTC, ZQUEMA requested changes
You have to answer the questions

2023-03-01 11:03 UTC, ZQUEMA commented on application/app_code/lib/pages/auth_linker/auth_linker_functional.dart
> +    String clientId = "7P3NMqftCBgr7H-XaPUbNg";
What's this hard ID ?

2023-03-01 11:03 UTC, ZQUEMA commented on server/server_app.js
> +    const authString = `7P3NMqftCBgr7H-XaPUbNg:gPFD-f_P2DNz8WVjm-Qwj21G8hS9KA`
What's is this hard auth token ?

2023-03-01 14:35 UTC, TomDUVAL-MAHE approved these changes, later dismissed

2023-03-01 15:06 UTC, ZQUEMA approved these changes, later dismissed

2023-03-01 15:12 UTC, LucasTesnier submitted a review, later dismissed

2023-03-01 16:30 UTC, TomDUVAL-MAHE submitted a review, later dismissed

2023-03-01 22:36 UTC, LucasTesnier approved these changes

2023-03-02 08:29 UTC, TomDUVAL-MAHE approved these changes

2023-03-02 08:30 UTC, merged