26 add gmail service
Epitech-Nantes-Tek3/A-equals-l-squared pull request #39
Opened 2023-01-24 12:08 UTC by GuyomT

# Purpose

The purpose of this pull request is to add the service gmail.

Fixes # (issue)

## Added features

* This service has been added to the application. It's include:
  * Sending an email to any person with the mail aequallsquared@gmail.com created for this project.

2023-01-24 13:51 UTC, LucasTesnier requested changes
+ Can you rename your gmail.js file to service.js or service_init.js ?
+ Did you format your JS Code with the VS extension ?

2023-01-24 13:51 UTC, LucasTesnier commented on server/services/gmail/gmail.js
> +async function sendEmail(to, subject, body) {
in convention async is set after the function name.

2023-01-24 13:51 UTC, LucasTesnier commented on server/services/gmail/gmail.js
> +  console.log(`Email sent to ${to}!`);
Is it planned to be deleted in a future pr?

2023-01-25 08:36 UTC, LucasTesnier requested changes
Just 2 minor documentation error, otherwise NTR (Check your format)

2023-01-25 08:36 UTC, LucasTesnier commented on server/services/gmail/send_email.js
> + *
Missing function brief

2023-01-25 08:36 UTC, LucasTesnier commented on server/services/gmail/gmail_init.js
> + *
Missing function brief

2023-01-25 13:45 UTC, LucasTesnier approved these changes
NTR!

2023-01-25 13:46 UTC, TomDUVAL-MAHE approved these changes

2023-01-25 13:57 UTC, ZQUEMA approved these changes

2023-01-25 13:58 UTC, tbellicha approved these changes

2023-01-25 14:02 UTC, merged