34 create flutter objects class
Epitech-Nantes-Tek3/A-equals-l-squared pull request #44
Opened 2023-01-24 14:08 UTC by TomDUVAL-MAHE

**Short description:**
Create Flutter objects to store all data from the DB to use it in our app

**Describe the solution you'd like**

Create Flutter objects which get all data from JSON with an API call

Objects : 

- [x] 1. Error

> 1. Error message

- [x]  2. User

>1. Username
>2. E-mail
>3. Token auth
>4. is Admin
>5. Created At.

- [x] 3. Service

>1. Name
>2. Description
>3. Created At.

- [x] 4. Action

>1. Name
>2. Description
>3. Created At.
>4. Is Enable.

- [x] 5. Reaction

>1. Name
>2. Description
>3. Created At.
>4. Is Enable.

Add tests for classes : 

- [x] User

2023-01-24 15:05 UTC, ZQUEMA submitted a review, later dismissed

2023-01-24 19:14 UTC, LucasTesnier requested changes
A lot of minor things.
By the way, your unit testing can't work !
You only need to have one main function calling all your unit function.
Go to discord for more informations

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/action_data.dart
> +/// It contains all information about a action
An ?

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/action_data.dart
> +  final String name;
Final ? See discord

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/action_data.dart
> +        createdAt: json["action"]["createdAt"],
Please use simple quote

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/error_data.dart
> +      errorMessage: json['errorMessage'],
An error does'nt have a field

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/reaction_data.dart
> +        createdAt: json["reaction"]["createdAt"],
Quote

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/service_data.dart
> +      createdAt: json["service"]["createdAt"],
Quote

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/user_data.dart
> +  final String token;
Make it null possible with ?

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/user_data.dart
> +    required this.token,
Not required

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/user_data.dart
> +        createdAt: json["user"]["createdAt"],
Quote

2023-01-24 19:14 UTC, LucasTesnier commented on application/app_code/test/testsFlutterObjects/action_data_tests.dart
> +void templateFunction() {
Why did you put it in the template function ? 

Please create one function for each object.

By the way, try to respect the projet architecture in the tests directory

2023-01-25 13:08 UTC, LucasTesnier requested changes
Just one minor things, will talk about this right after the meeting

2023-01-25 13:08 UTC, LucasTesnier commented on application/app_code/lib/flutter_objects/user_data.dart
> +        token: json['token']);
make it optional

2023-01-25 13:35 UTC, LucasTesnier approved these changes

2023-01-25 13:56 UTC, ZQUEMA approved these changes

2023-01-25 14:01 UTC, merged