Add the searchEmails and the readEmail fct, add a way to add service in db
Epitech-Nantes-Tek3/A-equals-l-squared pull request #55
Opened 2023-01-26 13:57 UTC by GuyomT

# Purpose

The purpose of this pull request is to add the action search email from the service gmail
and the way to create the service gmail in the database.

Fixes # (issue)

## Added features

* This service has been added to the application. It includes:
  * A action which is used to search for an email following the api query format (an example in on discord in the gmail channel)
  * A function to create the service with prisma in the db

2023-01-27 23:31 UTC, LucasTesnier requested changes
What's the utility of searchEmail function is she doesn't return anything ?

Please create some documentation

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/actions/read_email.js
> +async function readEmail(emailId) {
Missing documentation

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/actions/read_email.js
> +async function searchEmails(query) {
Missing documentation

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/actions/read_email.js
> +      // iterate through the messages and get the id
Useless documentation

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/actions/read_email.js
> +        console.log(email.data.id)
Please remove console.log when merging to main

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/actions/read_email.js
> +      console.log('No email found.');
Use some return keyword and not console.log

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/gmail_init.js
> +function createGmailService() {
Missing documentation

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/gmail_init.js
> +    description: 'Gmail service',
It will be updated in part 2 ?

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/gmail_init.js
> +      description: 'Read an email',
Same ?

2023-01-27 23:31 UTC, LucasTesnier commented on server/services/gmail/gmail_init.js
> +      description: 'Send an email',
Same ?

2023-01-29 19:13 UTC, TomDUVAL-MAHE approved these changes, later dismissed
NTR, but you have conflicts !

2023-01-29 20:26 UTC, LucasTesnier approved these changes

2023-01-29 21:38 UTC, ZQUEMA approved these changes

2023-01-29 21:42 UTC, merged