56 add Actions/Reaction parameters in the database
Epitech-Nantes-Tek3/A-equals-l-squared pull request #62
Opened 2023-01-27 15:21 UTC by ZQUEMA

# Purpose

The purpose of this pull request is to add actions and reaction parameters in the database architecture.

Fixes #56

## Added features

* New tables are available:
* Parameter: This table stores the differents parameters without the value for the Actions and Reactions.
* ActionParameter: This table is used to store the value of the Action's parameters, and this table is used in UserHasActionsReactions model.
* ReactionParameter: This table is used to store the value of the Reaction's parameters, and this table is used in UserHasActionsReactions model.

## Updated features

* UserHasActionsReactions model has now to new relations with ActionParameters and ReactionParamaters. These tables allow to store the parameters used by the actions and reaction for each A/REA wanted by the user.

## Removed features
* The model ActionTriggers does not exist anymore. It was useless because Parameter models are more permissive.

2023-01-27 15:46 UTC, tbellicha requested changes

2023-01-27 15:46 UTC, tbellicha commented on server/prisma/schema.prisma
> +  ReactionParameter ReactionParameter[]
`ReactionParameter` to `ReactionParameters`

2023-01-27 15:46 UTC, tbellicha commented on server/prisma/schema.prisma
> +  ActionParameter   ActionParameter[]
`ActionParameter` to `ActionParameters`

2023-01-27 15:46 UTC, tbellicha commented on server/prisma/schema.prisma
> +  ReactionParameter ReactionParameter[]
`ReactionParameter` to `ReactionParameters`

2023-01-27 15:51 UTC, tbellicha approved these changes

2023-01-27 16:16 UTC, LucasTesnier requested changes
Just a typo lol

2023-01-27 16:16 UTC, LucasTesnier commented on server/prisma/schema.prisma
> +  output   = "../docs/prisma"
Trailing space

2023-01-28 20:03 UTC, tbellicha approved these changes

2023-01-29 14:05 UTC, ZQUEMA commented on server/prisma/schema.prisma
> +  output   = "../docs/prisma"
That's not a trailling space 
It's the code format of prisma. The second column should be with the same indentation.

2023-01-29 17:40 UTC, TomDUVAL-MAHE approved these changes
NTR

2023-01-29 18:10 UTC, LucasTesnier approved these changes

2023-01-29 18:58 UTC, merged