47 design connection page
Epitech-Nantes-Tek3/A-equals-l-squared pull request #67
Opened 2023-01-30 17:26 UTC by TomDUVAL-MAHE

# Purpose

This pull request brings the overall design of the login page. It must be improved later. Sorry for the size of the commits, which are also poorly linked.

Close #47 

![image](https://user-images.githubusercontent.com/72017980/215549460-312150c1-b78b-4e30-9eb5-ea55c0a97258.png)

![image](https://user-images.githubusercontent.com/72017980/215549498-ae74fecc-a412-4161-a0b1-04d669da70de.png)

2023-01-30 20:07 UTC, LucasTesnier requested changes
Answer ??? And add documentation, otherwise NTR

2023-01-30 20:07 UTC, LucasTesnier commented on application/app_code/lib/main.dart
> +        /// Change to color materialColorBlueForArea()
??

2023-01-30 20:07 UTC, LucasTesnier commented on application/app_code/lib/pages/signup/signup_state.dart
> +  Widget displayLogo() {
Missing doc

2023-01-31 07:28 UTC, LucasTesnier requested changes
Missing doc

2023-01-31 07:28 UTC, LucasTesnier commented on application/app_code/lib/pages/login/login_state.dart
> +  bool _isConnexionWithEmail = false;
Missing doc my bad

2023-01-31 07:28 UTC, LucasTesnier commented on application/app_code/lib/pages/login/login_state.dart
> +  /// These function display the button for request a new password
These ?

2023-01-31 07:28 UTC, LucasTesnier commented on application/app_code/lib/pages/signup/signup_state.dart
> +  Widget displayLogo() {
Up

2023-01-31 10:07 UTC, ZQUEMA approved these changes

2023-01-31 10:14 UTC, LucasTesnier approved these changes

2023-01-31 10:14 UTC, merged