69 create the area relations
Epitech-Nantes-Tek3/A-equals-l-squared pull request #79
Opened 2023-01-31 16:15 UTC by ZQUEMA

# Purpose

This PR add the possibility to create a A/REA relation.

Fixes #69 

## Added features

* It adds many dev routes to create some entities
  * User -> /api/dev/user/create 
  * Service -> /api/dev/user/service 
  * Action -> /api/dev/user/action 
  * Reaction -> /api/dev/user/reaction
  * Parameter -> /api/dev/user/parameter
* It add the route /api/area/create to create a A/REA relation

2023-02-01 07:42 UTC, tbellicha requested changes
Missing documentation on all implemented functions

2023-02-01 08:24 UTC, LucasTesnier requested changes
ANswer my question, remove useless login, document your code and please use the correct format (CF Discord channel)

2023-02-01 08:24 UTC, LucasTesnier commented on server/server_app.js
> +app.use(session({ secret: 'SECRET', resave: false, saveUninitialized: false }))
Why did you updated that ?

2023-02-01 08:24 UTC, LucasTesnier commented on server/server_app.js
> +  console.log(req.body)
Why did you log the body ?

2023-02-01 08:24 UTC, LucasTesnier commented on server/server_app.js
> +app.post('/api/dev/user/create', async (req, res) => {
Documentation

2023-02-01 08:24 UTC, TomDUVAL-MAHE requested changes
Missing doc 
Bad format

2023-02-01 09:55 UTC, ZQUEMA commented on server/server_app.js
> +app.use(session({ secret: 'SECRET', resave: false, saveUninitialized: false }))
Don't know
It's may be the auto-format

2023-02-01 18:57 UTC, TomDUVAL-MAHE submitted a review, later dismissed
Seems good to me

2023-02-02 08:33 UTC, LucasTesnier approved these changes

2023-02-02 08:40 UTC, tbellicha approved these changes

2023-02-02 08:44 UTC, merged